### ISSUE TITLE
Qual a fonte das informações?

### ISSUE THREAD

**Issue by jeancsanchez** [vitimdt/TraderExpert#3]
Olá. Ótimo código. Parabéns :)

Qual site você está usando pra pegar as cotações?

**Comment by vitimdt** [comment]
Oi @jeancsanchez . Obrigado!
A configuração que funciona pra pegar as cotações é pelo site da InfoMoney.

**Comment by jeancsanchez** [comment]
@vitimdt  Legal!!!
Outra coisa: teria como subir um arquivo `requirements.txt` com as dependências do projeto?

**Comment by vitimdt** [comment]
@jeancsanchez , adicionei os arquivos.
